baseURL = "https://my.fesco.com/help"
# languageCode = "en-us"
title = "Fesco Help"
theme = "pixxett"
MetaDataFormat = "toml"
Paginate = 10
DefaultContentLanguage = "ru"
# defaultContentLanguageInSubdir= true

[taxonomies]
  tag = "tags"

[languages]
  [languages.ru]
    # baseUrl = "https://my.fesco.com/help"
    weight = 1
    languageName = "Russian"

  [languages.en]
    # baseUrl = "https://my.fesco.com/help/en"
    weight = 0
    languageName = "English"




